name: Feature Request
description: For feature requests regarding the Flipper Zero firmware.
labels: ['feature request']
body:
- type: textarea
  id: proposal
  attributes:
    label: "Description of the feature you're suggesting"
    description: |
      Please describe your feature request in as many details as possible.
        - Describe what it should do
        - Note whetever it is to extend existing functionality or introduce new functionality.
  validations:
    required: true
- type: textarea
  id: anything-else
  attributes:
    label: Anything else?
    description: Let us know if you have anything else to share.
